layout: null
title: Upphack [2021]
description: Start page for Upphack 2021 event
theme: jekyll-theme-cayman
locale: "sv_SE"
social-network-links:
  email: "info@it-huset.se"
  github: https://github.com/IT-HUSET
  twitter: weareithuset
  linkedin: https://www.linkedin.com/company/52337
  instagram: weareithuset
